### ISSUE TITLE
Swift5.0.1 update

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [nih-at/Getopt#1]
A few things are needed to make this work with Swift5.0.1:
1) A Package.swift
2) Some rearrangement of where things are.
3) Update the code wrt redefinition of 'Range' types.
4) In `./Tests`, a new file `LinuxMain.swift` is needed.

1. Package.swift needs something like this:

`

    // swift-tools-version:5.0
    // The swift-tools-version declares the minimum version of Swift required to build this package.
    
    import PackageDescription
    
    let package = Package(
        name: "Getopt",
        products: [
            // Products define the executables and libraries produced by a package, and make them visible to other packages.
            .library(
                name: "Getopt",
                targets: ["Getopt"]),
        ],
        dependencies: [
            // Dependencies declare other packages that this package depends on.
            // .package(url: /* package url */, from: "1.0.0"),
        ],
        targets: [
            // Targets are the basic building blocks of a package. A target can define a module or a test suite.
            // Targets can depend on other targets in this package, and on products in packages which this package depends on.
            .target(
                name: "Getopt",
                dependencies: []),
            .testTarget(
                name: "GetoptTests",
                dependencies: ["Getopt"]),
        ]
    )

2. The `Getopt` folder needs to go under `./Sources`, and `GetoptTests` needs to go under `./Tests`.

3. Using the file structure in (2) above, Sources/Getopt/Getopt.swift (line 295) needs to be changed
**from**:
`if let range = argument.rangeOfCharacter(from: equal, options: [], range: Range(index ..< argument.endIndex)) {`
**to**:
`if let range = argument.rangeOfCharacter(from: equal, options: [], range: index ..< argument.endIndex) {`  
*Refer to:*  https://stackoverflow.com/questions/50714543/cannot-invoke-initializer-for-type-rangestring-index-with-an-argument-list-o

4. `LinuxMain.swift` was generated by using `swift package generate-xcodeproj`.  The file's contents are:

`

    import XCTest

    import GetoptTests

    var tests = [XCTestCaseEntry]()
    tests += GetoptTests.allTests()
    XCTMain(tests)
